import React from 'react';

const index = () => {
  const data = {
    total_count: 5,
    incomplete_results: false,
    items: [
      {
        login: 'torvalds',
        id: 1024025,
        node_id: 'MDQ6VXNlcjEwMjQwMjU=',
        avatar_url: 'https://avatars.githubusercontent.com/u/1024025?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/torvalds',
        html_url: 'https://github.com/torvalds',
        followers_url: 'https://api.github.com/users/torvalds/followers',
        following_url: 'https://api.github.com/users/torvalds/following{/other_user}',
        gists_url: 'https://api.github.com/users/torvalds/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/torvalds/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/torvalds/subscriptions',
        organizations_url: 'https://api.github.com/users/torvalds/orgs',
        repos_url: 'https://api.github.com/users/torvalds/repos',
        events_url: 'https://api.github.com/users/torvalds/events{/privacy}',
        received_events_url: 'https://api.github.com/users/torvalds/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
        score: 1.0,
      },
      {
        login: 'yyx990803',
        id: 499550,
        node_id: 'MDQ6VXNlcjQ5OTU1MA==',
        avatar_url: 'https://avatars.githubusercontent.com/u/499550?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/yyx990803',
        html_url: 'https://github.com/yyx990803',
        followers_url: 'https://api.github.com/users/yyx990803/followers',
        following_url: 'https://api.github.com/users/yyx990803/following{/other_user}',
        gists_url: 'https://api.github.com/users/yyx990803/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/yyx990803/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/yyx990803/subscriptions',
        organizations_url: 'https://api.github.com/users/yyx990803/orgs',
        repos_url: 'https://api.github.com/users/yyx990803/repos',
        events_url: 'https://api.github.com/users/yyx990803/events{/privacy}',
        received_events_url: 'https://api.github.com/users/yyx990803/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
        score: 1.0,
      },
      {
        login: 'karpathy',
        id: 241138,
        node_id: 'MDQ6VXNlcjI0MTEzOA==',
        avatar_url: 'https://avatars.githubusercontent.com/u/241138?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/karpathy',
        html_url: 'https://github.com/karpathy',
        followers_url: 'https://api.github.com/users/karpathy/followers',
        following_url: 'https://api.github.com/users/karpathy/following{/other_user}',
        gists_url: 'https://api.github.com/users/karpathy/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/karpathy/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/karpathy/subscriptions',
        organizations_url: 'https://api.github.com/users/karpathy/orgs',
        repos_url: 'https://api.github.com/users/karpathy/repos',
        events_url: 'https://api.github.com/users/karpathy/events{/privacy}',
        received_events_url: 'https://api.github.com/users/karpathy/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
        score: 1.0,
      },
      {
        login: 'gustavoguanabara',
        id: 8683378,
        node_id: 'MDQ6VXNlcjg2ODMzNzg=',
        avatar_url: 'https://avatars.githubusercontent.com/u/8683378?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/gustavoguanabara',
        html_url: 'https://github.com/gustavoguanabara',
        followers_url: 'https://api.github.com/users/gustavoguanabara/followers',
        following_url: 'https://api.github.com/users/gustavoguanabara/following{/other_user}',
        gists_url: 'https://api.github.com/users/gustavoguanabara/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/gustavoguanabara/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/gustavoguanabara/subscriptions',
        organizations_url: 'https://api.github.com/users/gustavoguanabara/orgs',
        repos_url: 'https://api.github.com/users/gustavoguanabara/repos',
        events_url: 'https://api.github.com/users/gustavoguanabara/events{/privacy}',
        received_events_url: 'https://api.github.com/users/gustavoguanabara/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
        score: 1.0,
      },
      {
        login: 'openai',
        id: 14957082,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjE0OTU3MDgy',
        avatar_url: 'https://avatars.githubusercontent.com/u/14957082?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/openai',
        html_url: 'https://github.com/openai',
        followers_url: 'https://api.github.com/users/openai/followers',
        following_url: 'https://api.github.com/users/openai/following{/other_user}',
        gists_url: 'https://api.github.com/users/openai/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/openai/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/openai/subscriptions',
        organizations_url: 'https://api.github.com/users/openai/orgs',
        repos_url: 'https://api.github.com/users/openai/repos',
        events_url: 'https://api.github.com/users/openai/events{/privacy}',
        received_events_url: 'https://api.github.com/users/openai/received_events',
        type: 'Organization',
        user_view_type: 'public',
        site_admin: false,
        score: 1.0,
      },
    ],
  };

  return <div>index</div>;
};

export default index;
